### ISSUE TITLE
Feature Request: Add Tabs

### ISSUE THREAD

**Issue by Ahmadhosseinbor** [KorbsStudio/Penpot-Desktop#11]
To open multiple files like Figma-Desktop

**Comment by KorbsStudio** [comment]
I'll look into this and I also think it should be added. 
It also would help with minor things as well

**Comment by KorbsStudio** [comment]
Work in progress! 

https://user-images.githubusercontent.com/51213244/192071215-a26335ac-244b-48dd-a4ce-2921d051feb7.mp4

**Comment by KorbsStudio** [comment]
Hi there @brrd! I'm implementing your [electron-tabs](https://github.com/brrd/electron-tabs) library into Penpot Desktop, since it's been requested.

I have got it working, but with some issues.

1. Unable to automatically change name of new tabs. A fix you've provided [here](https://github.com/brrd/electron-tabs/issues/73#issuecomment-477182904) only works for first opened tab, and that tab only. It won't work for new tabs, sadly. 

     I need this to work so people can navigate between projects easily by seeing the project name in the tab.

3. When opening links (that contain `target='_blank'`), new tabs for those do open. However, the code your provided [here](https://github.com/brrd/electron-tabs/issues/106#issuecomment-636300549) does mostly work, but I would like to at least prevent a new window from opening.

![image](https://user-images.githubusercontent.com/51213244/192072796-430d2cdc-68e0-422b-bfce-3a20bcd4e852.png)

**Comment by KorbsStudio** [comment]
I'm very excited to say, that I got everything to work and it should be released later in `v0.0.9`

https://user-images.githubusercontent.com/51213244/192087659-b79542b1-47b8-42fe-8296-ef1059509e8d.mp4
