### ISSUE TITLE
Bug: Maximise window icon/button not working on Windows 10

### ISSUE THREAD

**Issue by knightknight** [KorbsStudio/Penpot-Desktop#14]
Version: 0.0.6 Alpha

Maximise window icon/button not working on Windows 10.

**Comment by KorbsStudio** [comment]
Strange, this is the native buttons you're seeing and it's not working?
Hmm, seems I need to setup a new Windows VM and investigate the issue.

**Comment by KorbsStudio** [comment]
I'm looking into this now. 

![image](https://user-images.githubusercontent.com/51213244/191382632-904d816a-f9e3-45bf-bf3c-243d49b9cb32.png)

**Comment by KorbsStudio** [comment]
Hi there, the maximize button may of been broken because of the `transparent` option I used in Electron. So instead, I installed the Glasstron package and disabled the `transparent` option, and that the button now seems to work.

This fix will be released `v0.0.7`.

https://user-images.githubusercontent.com/51213244/191388197-857c6c22-68d8-4bab-84f3-4989de765144.mp4
